backend:
  name: git-gateway
  branch: content
  identity_url: https://gotrue.ecomplus.biz/51488/.netlify/identity
  gateway_url: https://gitgateway.ecomplus.biz/51488/.netlify/git
media_folder: media/uploads
collections:
  - name: institutional-pages
    label: Institutional Pages
    identifier_field: name
    extension: md
    format: frontmatter
    folder: content/pages
    create: true
    path: '{{group}}/{{slug}}/index'
    fields:
      - name: title
        label: Título
        widget: string
      - name: meta_title
        label: Meta Título
        widget: string
      - name: meta_description
        label: Meta Descrição
        widget: string
      - name: publishedAt
        label: Publicado em
        widget: datetime
      - name: body
        label: Conteúdo
        widget: markdown
      - name: group
        label: Grupo
        widget: select
        options:
          - institucional
          - pedidos
